# -*- coding: utf-8 -*-
"""ASD_Hyperparameters.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AJb1DMPuA243PwBjePrBqoZBFNQ3Roo1
"""

# Parameters
sample_rate = 16000      # Standard for speech  16000
duration = 0.5           # Duration of each chunk (second) = 50ms ? 500ms
hop_length = 0.1         # Overlap between chunks (second) = 100ms
batch_size = 96         # Dataloader for pre-training and fine-tuning
target_batch_size = 128  # Dataloader for validation and testing   64 128 256

d_model = 256              # for raw audio 768 and spectrom 512
nhead = 2                  # number of head mecanism of self-attention 8
dim_feedforward = 4 * d_model      # 4*d_model 3072     embed_dim must be divisible by num_heads, 4 fois risque overfitting
num_layers = 4             # 6 to test 2
dropout = 0.2              # 0.1  transformers   0.3-0.5 for dense layers  0.2 to test
TSlength_aligned = int(sample_rate * duration)  # 8000 vs 800
patch_size = 8000
stride = 8000
num_epoch_pretrain = 0           # 25 50 100
num_epoch_finetune = 20           # 25 50 100
lr = 3e-5                # 1e-4 to test 3e-4  5e-4 3e-6
lr_classifier = 3e-5

num_classes_target = 2   # asd vs nonasd

context_cont_temperature = 0.2
context_cont_use_cosine_similarity = True

experiment_log_dir = "/content/drive/MyDrive/TFC/Save_dataset/"
data_dir = "/content/drive/MyDrive"
targetdata_path = "/content/drive/MyDrive/TFC/Save_dataset/"
sourcedata_path = targetdata_path  #data is the same for pre training and fine training

folder_ASD = "TFC/Folder_ASD/training_10"
folder_sktd = "TFC/Folder_nonASD/training_sktd_10"
folder_adhd = "TFC/Folder_nonASD/training_adhd_10"
folder_ASD_recanvo = "Autism_Dataset/Recanvo_train_samples8_150"      # All ReCANVo data  Recanvo_train_samples8_150
folder_ASD_uclass = "Autism_Dataset/Uclass12MF"

folder_sktd_t = "TFC/Folder_nonASD_t/testing_sktd_10"
folder_adhd_t = "TFC/Folder_nonASD_t/testing_adhd_10"
folder_ASD_t = "TFC/Folder_ASD_t/testing_10"                         # Testing Dutch only

save_train_path = "/content/drive/MyDrive/TFC/Save_dataset/pretrain/train.pt"
save_test_path = "/content/drive/MyDrive/TFC/Save_dataset/pretrain/test.pt"

filename_map = {}

import os
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.model_selection import GroupKFold
import numpy as np
from pathlib import Path
from torch.utils.data import Dataset, DataLoader
import torch
import random

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed) # Pour le multi-GPU
    # Assure un déterminisme total sur les algorithmes de convolution
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)