# -*- coding: utf-8 -*-
"""ASD_Utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RyA8uPrBLKZN_yamGkBY3XnB4vTk8e4j
"""

########################################################################
"""
def model_validate(model, valid_dl, device, classifier):

    model.eval()
    classifier.eval()

    criterion = nn.CrossEntropyLoss()

    total_loss = []
    total_acc = []

    with torch.no_grad():

        for data, labels, _, data_f, _, _, _ in valid_dl:

            data = data.float().to(device)
            labels = labels.long().to(device)
            data_f = data_f.float().to(device)

            # Forward pass
            h_t, z_t, h_f, z_f = model(data, data_f)

            z_t = F.normalize(z_t, dim=1)
            z_f = F.normalize(z_f, dim=1)

            # SupCon embeddings
            features_supcon = torch.cat(
                [z_t.unsqueeze(1), z_f.unsqueeze(1)],
                dim=1
            )

            criterion_supcon = SupConLoss()
            l_supcon = criterion_supcon(features_supcon, labels)

            # Classification
            fea_concat = torch.cat((z_t, z_f), dim=1)

            predictions = classifier(fea_concat)

            loss_cls = criterion(predictions, labels)

            alpha = 1.0
            loss = alpha * l_supcon + loss_cls

            acc = labels.eq(
                predictions.argmax(dim=1)
            ).float().mean()

            total_loss.append(loss.item())
            total_acc.append(acc.item())

    avg_loss = np.mean(total_loss)
    avg_acc = np.mean(total_acc)

    print(f' Validation: loss={avg_loss:.4f} | Acc={avg_acc*100:.2f}')

    return avg_loss, avg_acc
"""
##########################################################################


import pandas as pd
import os
import src.utils.hyperparameters_asd as cfg

def get_file_type(filename):
    """Détermine si le fichier commence par un chiffre ou une lettre."""
    if not filename or not isinstance(filename, str):
        return "Inconnu"

    first_char = filename[0]
    if first_char.isdigit():
        return "Chiffre"
    elif first_char.isalpha():
        return "Lettre"
    else:
        return "Autre"

########################################################################
def print_metrics_prediction(output_csv_path):
    """Charge le CSV et affiche les statistiques d'exactitude par groupe."""
    # 1. Charger le fichier CSV
    try:
        df = pd.read_csv(output_csv_path)
    except FileNotFoundError:
        print(f"Erreur : Le fichier {output_csv_path} est introuvable.")
        return

    # 2. Appliquer la fonction pour créer une nouvelle colonne de groupe
    df['group_type'] = df['filename'].apply(get_file_type)

    # 3. Calculer les statistiques par groupe
    # On calcule le nombre de corrects et le total par groupe
    summary = df.groupby('group_type').agg(
        Total=('status', 'count'),
        Corrects=('status', lambda x: (x == 'CORRECT').sum())
    )

    # 4. Calculer le pourcentage
    summary['Accuracy (%)'] = (summary['Corrects'] / summary['Total']) * 100

    # Affichage des résultats
    print("\n" + "="*50)
    print("--- ANALYSE DE L'EXACTITUDE PAR TYPE DE FICHIER ---")
    print("="*50)

    # Affichage détaillé pour le rapport
    for group, row in summary.iterrows():
        print(f"\nGroupe '{group}':")
        print(f"  - Rapport   : {int(row['Corrects'])} / {int(row['Total'])} corrects")
        print(f"  - Précision : {row['Accuracy (%)']:.2f}%")
    print("\n" + "="*50)

###########################################################################
def analyze_accuracy_by_type(csv_path, id_column='filename'):
    """Calcule l'exactitude selon les datasets: Dutch / ReCanvo."""
    df = pd.read_csv(csv_path)

    def get_type(x):
        if str(x)[0].isdigit(): return "RECANVO (ASD)"
        if str(x)[0].isalpha(): return "DUTCH (SK_ASD + SK_TD + SK_ADHD )"
        return "Autre"

    df['group_type'] = df[id_column].apply(get_type)

    # Agrégation optimisée
    stats = df.groupby('group_type')['status'].agg(
        Total='count',
        Corrects=lambda s: (s == 'CORRECT').sum()
    )
    stats['Accuracy (%)'] = (stats['Corrects'] / stats['Total'] * 100).round(2)

    print(f"\n Rapport d'analyse pour : {os.path.basename(csv_path)}")
    print("-" * 50)
    print(stats)
    return stats

#def one_hot_encoding(X):
#    X = [int(x) for x in X]
#    n_values = np.max(X) + 1
#    b = np.eye(n_values)[X]
#    return b

########################################################################
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import numpy as np
import torch
import re

def visualization_tsne(emb, lab, filenm, filename_map, ep, acc, precision, recall, f1, train_mode):
    """
    emb : (N, D)  torch.Tensor ou np.ndarray
    lab : (N,)    torch.Tensor ou np.ndarray, 0 = NonASD, 1 = ASD
    filenm : (N, L) torch.Tensor de tokens
    filename_map : dict {tuple(token_ids): filename_str}
    """

    # --- conversions numpy ---
    if isinstance(emb, torch.Tensor):
        emb = emb.detach().cpu().numpy()
    if isinstance(lab, torch.Tensor):
        lab = lab.detach().cpu().numpy()
    if isinstance(filenm, torch.Tensor):
        filenm_np = filenm.detach().cpu().numpy()
    else:
        filenm_np = filenm

    N = emb.shape[0]


    # --- reconstruire les noms de fichiers ---
    filenames = []
    for i in range(N):
        key = tuple(filenm_np[i].tolist())
        fname = filename_map.get(key, "")
        filenames.append(fname)
    filenames = np.array(filenames)

    # --- masques sur les classes ---
    lab = np.array(lab)
    mask_asd = (lab == 1)      # ASD
    mask_nonasd = (lab == 0)   # NonASD

    # --- au sein de ASD : deux sous-ensembles par préfixe ---
    pattern_digits = re.compile(r"^[0-9]{6}")   # ex: 200122_1453_...
    pattern_letter = re.compile(r"^[A-Za-z]")   # ex: adhd36_...

    mask_asd_digits = np.zeros(N, dtype=bool)
    mask_asd_letters = np.zeros(N, dtype=bool)

    for i, fname in enumerate(filenames):
        if not mask_asd[i]:
            continue
        if pattern_digits.match(fname):
            mask_asd_digits[i] = True
        elif pattern_letter.match(fname):
            mask_asd_letters[i] = True

    print("Total N :", N)
    print("ASD total (lab==1):", mask_asd.sum())
    print("NONASD total (lab==0):", mask_asd.sum())
    print("ASD_digits :", mask_asd_digits.sum())
    print("ASD_letters:", mask_asd_letters.sum())

    # (éventuelles ASD qui ne matchent ni digits ni letter au début)
    mask_asd_other = mask_asd & ~(mask_asd_digits | mask_asd_letters)

    print("ASD_other  :", mask_asd_other.sum())

    idx_asd_other = np.where(mask_asd_other)[0]
    print("Quelques ASD_other:", idx_asd_other[:20])
    for i in idx_asd_other[:20]:
        print(i, repr(filenames[i]), "label:", lab[i])

    # --- t-SNE sur tous les embeddings ---
    reducer = TSNE(
        n_components=2,
        perplexity=20,
        learning_rate='auto',
        init='pca',
        metric='euclidean',
        n_iter=500,
        random_state=42
    )
    embedding_2d = reducer.fit_transform(emb)

    plt.figure(figsize=(8, 6))

    # 1) NonASD (classe 0) :
    idx_nonasd = np.where(mask_nonasd)[0]
    if len(idx_nonasd) > 0:
        plt.scatter(
            embedding_2d[idx_nonasd, 0],
            embedding_2d[idx_nonasd, 1],
            c='tab:blue',
            s=10,
            alpha=0.8,
            label='NonASD (label 0)'
        )

    # 2) ASD dataset 1 (6 chiffres au début Recanvo)
    combined_mask = mask_asd_other | mask_asd_digits

    if combined_mask.any():
        plt.scatter(
            embedding_2d[combined_mask, 0],
            embedding_2d[combined_mask, 1],
            c='tab:red',
            s=10,
            alpha=0.9,
            marker='o',
            label='ASD (Recanvo, label 1)'
        )

    # 3) ASD dataset 2 (lettre au début Dutch)
    idx_asd_letters = np.where(mask_asd_letters)[0]
    if len(idx_asd_letters) > 0:
        plt.scatter(
            embedding_2d[idx_asd_letters, 0],
            embedding_2d[idx_asd_letters, 1],
            c='tab:orange',
            s=10,
            alpha=0.5,
            marker='o',                    #'^'
            label='ASD (Dutch, label 1)'
        )

    # 4) ASD restant (optionnel) en violet pâle
    #idx_asd_other = np.where(mask_asd_other)[0]
    #if len(idx_asd_other) > 0:
    #    plt.scatter(
    #        embedding_2d[idx_asd_other, 0],
    #        embedding_2d[idx_asd_other, 1],
    #        c='mediumpurple',
    #        s=20,
    #        alpha=0.7,
    #        label='ASD autres (label 1)'
    #    )

    plt.title(
        #f't-SNE embeddings lr:{lr} Acc:{acc.4f} Precision:{precision.4f} Recall:{recall.4f} F1:{f1.4f} (Epoch {ep})'
        f't-SNE embeddings lr:{cfg.lr} Acc:{acc:.4f} Precision:{precision:.4f} Recall:{recall:.4f} F1:{f1:.4f} (Epoch {ep})'
    )
    plt.xlabel("t-SNE-1")
    plt.ylabel("t-SNE-2")
    plt.grid(True)
    plt.legend(loc='best')
    plt.tight_layout()

    plt.savefig(
        f'/content/drive/MyDrive/TFC/Save_dataset/TSNE/'
        f'fig_supconv1_{train_mode}_epoch_{ep}_ASDdigits_ASDletters_NonASD.png'
    )
    plt.close()

########################################################################
from sklearn.manifold import TSNE
import numpy as np
import torch
import re

class MetricTracker:
    def __init__(self):
        self.best_metrics = None
        self.best_epoch = 0
        self.best_score = -1

    def update(self, metrics, epoch, key='accuracy'):
        """Update best metrics based on selected key metric"""
        current_score = metrics[key]

        if current_score > self.best_score:
            self.best_score = current_score
            self.best_epoch = epoch
            self.best_metrics = metrics.copy()
            #print(f"New best {key} at epoch {epoch}: {current_score:.4f}")

    def print_best(self, metrics=None): # Le paramètre metrics est optionnel ici car on veut le BEST
        """Print and return the best metrics achieved"""
        if self.best_metrics is None:
            print("No metrics tracked yet.")
            return None

        print(f"--- Best Results Achieved at epoch {self.best_epoch} ---")
        # On appelle print_metrics et on retourne son résultat
        return print_metrics(self.best_metrics, self.best_epoch)


def print_metrics(metrics, epoch=None):
    """Print metrics dictionary in a readable format"""
    # Main metrics

    print(f"-----MLP Best Testing Perf at epoch {epoch} : "
      f"Acc={metrics['accuracy']*100:.4f}| "
      f"Precision={metrics['precision']*100:.4f} | "
      f"Recall={metrics['recall']*100:.4f} | "
      f"F1={metrics['f1']*100:.4f} | "
      f"AUROC={metrics['auroc']*100:.4f} | "
      f"AUPRC={metrics['auprc']*100:.4f}")
    return metrics

########################################################################