# -*- coding: utf-8 -*-
"""ASD_main_kfold.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P45AhypDhCe4zM_6OCU32kmYMP66zF67
"""

def run_kfold(file_paths, labels, groups_kfold, domains, k, data_dir=data_dir, batch_size=batch_size):

    print(f"\nTotal files .wav: {len(file_paths)}")
    print(f"Total unique individuals: {len(set(groups_kfold))}")
    sgkf = StratifiedGroupKFold(
        n_splits=k,
        shuffle=True,
        random_state=42
    )
    fold_results_testing = []
    fold_results_finetune = []
    for fold, (train_idx, val_idx) in enumerate(
            sgkf.split(file_paths, labels, groups_kfold)):

        print(f"\n================================================")
        print(f"=========== START FOLD {fold+1} ===============")
        print(f"================================================")

        train_files = file_paths[train_idx]
        val_files   = file_paths[val_idx]
        train_labels = labels[train_idx]
        val_labels   = labels[val_idx]
        train_groups = groups_kfold[train_idx]
        val_groups   = groups_kfold[val_idx]
        train_domains = domains[train_idx]
        val_domains = domains[val_idx]

        overlap = set(train_groups).intersection(set(val_groups))
        print(f"\nOverlap individuals between train/val: {len(overlap)}")
        if len(overlap) > 0:
            print("WARNING: SUBJECT LEAKAGE DETECTED!")
            print(overlap)

        print("\nTrain distribution:")
        print(f"Total unique train individuals: {len(set(train_groups))}")
        print(f"Class 0 (TD/ADHD): {np.sum(train_labels == 0)}")
        print(f"Class 1 (ASD/ReCANVo): {np.sum(train_labels == 1)}")

        print("\nValidation and test distribution:")
        print(f"Total unique validation individuals: {len(set(val_groups))}")
        print(f"Class 0 (TD/ADHD): {np.sum(val_labels == 0)}")
        print(f"Class 1 (ASD/ReCANVo): {np.sum(val_labels == 1)}")

        print("\nProcessing training set...\n")
        all_chunks, all_labels, all_filenames, all_groups, all_domains = process_folder(train_files, train_labels, train_groups, train_domains)
        print("\nBalancing training set...\n")
        all_chunks_balanced, \
        all_labels_balanced, \
        all_filenames_balanced, \
        all_groups_balanced, \
        all_domains_balanced = balance_dataset(
            all_chunks,
            all_labels,
            all_filenames,
            all_groups,
            all_domains
        )

        train_balanced = {
            'samples': all_chunks_balanced,
            'labels': all_labels_balanced,
            'filenames': all_filenames_balanced,
            'groups': all_groups_balanced,
            'domains': all_domains_balanced
        }
        """
        os.makedirs(os.path.join(sourcedata_path, 'pretrain'),
                    exist_ok=True)

        torch.save(
            train_balanced,
            os.path.join(
                sourcedata_path,
                'pretrain',
                f'mixed_train_fold_{fold+1}.pt'
            )
        )"""

        print("\nProcessing validation/test set...\n")

        all_chunks_t, all_labels_t, all_filenames_t, all_groups_t, all_domains_t = process_folder(val_files, val_labels, val_groups, val_domains)
        print("\nBalancing validation/test set...")

        all_chunks_t_balanced, \
        all_labels_t_balanced, \
        all_filenames_t_balanced, \
        all_groups_t_balanced, \
        all_domains_t_balanced = balance_dataset(
            all_chunks_t,
            all_labels_t,
            all_filenames_t,
            all_groups_t,
            all_domains_t
        )

        test_balanced = {
            'samples': all_chunks_t_balanced,
            'labels': all_labels_t_balanced,
            'filenames': all_filenames_t_balanced,
            'groups': all_groups_t_balanced,
            'domains': all_domains_t_balanced
        }
        # Without balancing in testing
        #test_no_balanced = {'samples': all_chunks_t, 'labels': all_labels_t, 'filenames': all_filenames_t, 'groups': all_groups_t}
        """
        os.makedirs(os.path.join(targetdata_path, 'pretrain'),
                    exist_ok=True)
        torch.save(
            test_balanced,
            os.path.join(
                targetdata_path,
                'pretrain',
                f'mixed_test_fold_{fold+1}.pt'
            )
        )"""

        print(f"Label distribution equilibree Train: 0={torch.sum(all_labels_balanced == 0).item()}, 1={torch.sum(all_labels_balanced == 1).item()}")
        print(f"Label distribution equilibree Test: 0={torch.sum(all_labels_t_balanced == 0).item()}, 1={torch.sum(all_labels_t_balanced == 1).item()}\n")

        # Load dataloaders
        #train_dl, test_dl = data_generator(train_balanced, test_no_balanced)
        train_dl, test_dl = data_generator(train_balanced, test_balanced)
        """
        batch = next(iter(train_dl))
        x_dataT, y_dataT, aug1_tdT, \
        x_data_fT, aug1_fdT, f_dataT = batch

        print("\nBatch shapes:")
        print("[Batch] Time-domain:", x_dataT.shape)
        print("[Batch] Labels:", y_dataT.shape)
        print("[Batch] Aug TD:", aug1_tdT.shape)
        print("[Batch] Frequency:", x_data_fT.shape)
        print("[Batch] Aug FD:", aug1_fdT.shape)
        print("[Batch] Filenames:", f_dataT.shape)

        # --- reconstruire les noms de fichiers dans un batch---

        #train_dl, valid_dl, test_dl = data_generator(sourcedata_path, targetdata_path)
        #batch = next(iter(test_dl))  # Correct way to access DataLoader content
        #x_data, y_data, aug1_td, x_data_f, aug1_fd, f_data = batch
        print("Filenames in the Batch for train dataloader:\n")
        filename_np = x_dataT.detach().cpu().numpy()
        filenames_np = []
        N = x_dataT.shape[0]
        for i in range(N):
          key = tuple(filename_np[i].tolist())
          fname_np = filename_map.get(key, "")
          filenames_np.append(fname_np)
          print(i, repr(fname_np), "label:", y_dataT[i])
        #filenames = np.array(filenames)"""

        device = torch.device(
            "cuda" if torch.cuda.is_available() else "cpu"
        )
        TFC_model = TFC().to(device)
        classifier = target_classifier().to(device)
        domain_classifier = DomainClassifier().to(device)
        #features_dim = 2*128  # Remplacez par la vraie dimension des embeddings TFC
        #domain_classifier = DomainClassifier(input_dim=features_dim, num_domains=3).to(device)

        domain_optimizer = torch.optim.Adam(
            domain_classifier.parameters(),
            #lr=1e-4
            lr=lr_classifier
        )
        model_optimizer = torch.optim.Adam(
            TFC_model.parameters(),
            lr=lr,
            betas=(0.9, 0.99),
            weight_decay=1e-4       #1e-4 to test 5e-4  1e-3
        )
        classifier_optimizer = torch.optim.Adam(
            classifier.parameters(),
            lr=lr_classifier,
            betas=(0.9, 0.99),
            weight_decay=1e-4
        )

        training_mode = "pre_train"
        Trainer(
            TFC_model,
            model_optimizer,
            classifier,
            classifier_optimizer,
            domain_classifier,
            domain_optimizer,
            train_dl,
            test_dl,
            device,
            experiment_log_dir,
            training_mode
        )

        training_mode = "fine_tune_validation_test"
        chkpoint = torch.load(
            os.path.join(experiment_log_dir, 'saved_models_supCon_pretrain', 'ckp_last.pt'),
            weights_only=True,
            map_location=device
        )
        pretrained_dict = chkpoint["model_state_dict"]
        TFC_model.load_state_dict(pretrained_dict)
        metrics_testing, metrics_finetune = Trainer(
            TFC_model,
            model_optimizer,
            classifier,
            classifier_optimizer,
            domain_classifier,
            domain_optimizer,
            train_dl,
            test_dl,
            device,
            experiment_log_dir,
            training_mode
        )

        fold_results_testing.append(metrics_testing)
        fold_results_finetune.append(metrics_finetune)

        training_mode = "prediction"
        classifier.load_state_dict(torch.load(os.path.join(experiment_log_dir, "saved_models_supCon_prediction", f'classifier_prediction.pt'), weights_only=True))
        TFC_model.load_state_dict(torch.load(os.path.join(experiment_log_dir, "saved_models_supCon_prediction", f'ckp_last_prediction.pt'), weights_only=True, map_location=device))
        Trainer(
            TFC_model,
            model_optimizer,
            classifier,
            classifier_optimizer,
            domain_classifier,
            domain_optimizer,
            train_dl,
            test_dl,
            device,
            experiment_log_dir,
            training_mode
        )

        print(f"\n=========== END FOLD {fold+1} ===========")


    accs_testing = [f['accuracy'] for f in fold_results_testing]
    f1s_testing = [f['f1'] for f in fold_results_testing]
    precs_testing = [f['precision'] for f in fold_results_testing]
    recs_testing = [f['recall'] for f in fold_results_testing]

    accs_finetune = [f['accuracy'] for f in fold_results_finetune]
    f1s_finetune = [f['f1'] for f in fold_results_finetune]
    precs_finetune = [f['precision'] for f in fold_results_finetune]
    recs_finetune = [f['recall'] for f in fold_results_finetune]

    print("\n" + "="*30)
    print("FINAL GLOBAL RESULTS IN FINETUNE")
    print("="*30)

    metrics_list_finetune = [('Accuracy', accs_finetune), ('Precision', precs_finetune), ('Recall', recs_finetune), ('F1-Score', f1s_finetune)]

    for name, values in metrics_list_finetune:
        mean_val = np.mean(values)
        std_val = np.std(values)
        print(f"{name}: {mean_val:.4f} ± {std_val:.4f}")

    print("\n" + "="*30)
    print("FINAL GLOBAL RESULTS IN TESTING")
    print("="*30)

    metrics_list_testing = [('Accuracy', accs_testing), ('Precision', precs_testing), ('Recall', recs_testing), ('F1-Score', f1s_testing)]

    for name, values in metrics_list_testing:
        mean_val = np.mean(values)
        std_val = np.std(values)
        print(f"{name}: {mean_val:.4f} ± {std_val:.4f}")

    # Affichage du BoxPlot multi-métriques
    plt.figure(figsize=(10, 6))
    plt.boxplot([accs_testing, precs_testing, recs_testing, f1s_testing], labels=['Accuracy', 'Precision', 'Recall', 'F1'])
    plt.title("Distribution des performances en prédiction sur 5-Folds (Datasets: Talk-bank, ReCANVo, UClass)")
    plt.ylabel("Score")
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()

    # ======================================================
    # Global Confusion Matrix Across All Folds
    # ======================================================

    global_cm = confusion_matrix(all_fold_y_true, all_fold_y_pred)

    global_cm_norm = global_cm.astype('float') / \
                    global_cm.sum(axis=1)[:, np.newaxis]

    print("\nGLOBAL CONFUSION MATRIX")
    print(global_cm)

    plt.figure(figsize=(7,6))

    sns.heatmap(
        global_cm,
        annot=True,
        fmt='d',
        cmap='Blues',
        xticklabels=['NonASD', 'ASD'],
        yticklabels=['NonASD', 'ASD']
    )

    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.title("Global Confusion Matrix Across 5-Fold CV")

    plt.tight_layout()
    plt.show()

    return fold_results_testing, fold_results_finetune



file_paths, labels, groups, domains, original_labels = build_dataset(data_dir)

asd_individuals = set()
recanvo_individuals = set()
td_individuals = set()
adhd_individuals = set()
uclass_f_individuals = set()
uclass_m_individuals = set()

for grp, lbl in zip(groups, original_labels):
    lbl = lbl.lower()
    if lbl == "asd":
        asd_individuals.add(grp)
    elif lbl == "p":
        recanvo_individuals.add(grp)
    elif lbl == "td":
        td_individuals.add(grp)
    elif lbl == "adhd":
        adhd_individuals.add(grp)
    elif lbl == "m":
        uclass_m_individuals.add(grp)
    elif lbl == "f":
        uclass_f_individuals.add(grp)

print("\nUnique individuals per class:")
print("ASD DUTCH:", len(asd_individuals))
print("ASD RECANVO:", len(recanvo_individuals))
print("TD DUTCH:", len(td_individuals))
print("ADHD DUTCH:", len(adhd_individuals))
print("UCLASS MEN:", len(uclass_m_individuals))
print("UCLASS WOMEN:", len(uclass_f_individuals))

Nb_NonASD = len(td_individuals) + len(adhd_individuals) + len(uclass_m_individuals) + len(uclass_f_individuals)
Nb_ASD = len(asd_individuals) + len(recanvo_individuals)
print(f"Total individuals: {len(set(groups))} with ASD: {Nb_ASD} , NonASD: {Nb_NonASD}")

print(f"Total samples .wav: {len(file_paths)}")
print("\nBinary sample distribution:")
print("ASD/ASD_RECANVO:", sum(labels))
print("TD/ADHD/UCLASS:", len(labels) - sum(labels))
all_fold_y_true = []
all_fold_y_pred = []
run_kfold(file_paths, labels, groups, domains, k=5)