# -*- coding: utf-8 -*-
"""ASD_Train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lISAuBU3vYn8MkdpJ8CpHerARt2zcg7x
"""

import torch
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, average_precision_score
from sklearn.metrics import precision_score, recall_score, f1_score
import torch.nn.functional as F
from torch import nn
from src.training.loss_asd import SupConLoss
#from src.evaluation.test_asd import model_test_individual_level, model_validate
#from src.utils.utils_asd import MetricTracker, analyze_accuracy_by_type, print_metrics
import src.datasets.dataloader_asd as dld

def model_pretrain(model, model_optimizer, domain_classifier, domain_optimizer, train_loader, device):
    total_loss = []
    model.train()
    domain_classifier.train()
    global loss, loss_t, loss_f, l_TF, loss_c, data_test, data_f_test
    #total_steps = num_epoch_finetune * len(train_loader)
    #current_step = 0
    total_domain_acc = 0.0
    num_batches = 0
    #model_optimizer.zero_grad()

    for batch_idx, (data, labels, aug1, data_f, aug1_f, _, domains) in enumerate(train_loader):
          data, labels = data.float().to(device), labels.long().to(device)
          aug1 = aug1.float().to(device)
          data_f, aug1_f = data_f.float().to(device), aug1_f.float().to(device)
          domains = domains.long().to(device)
          model_optimizer.zero_grad()     #new
          domain_optimizer.zero_grad()    #new
          #p = float(current_step) / total_steps
          # Appliquer la formule de Ganin et al.
          #current_alpha = 2.0 / (1.0 + np.exp(-10 * p)) - 1.0


          """Produce embeddings"""
          h_t, z_t, h_f, z_f = model(data, data_f)
          h_t_aug, z_t_aug, h_f_aug, z_f_aug = model(aug1, aug1_f)

          z_t = F.normalize(z_t, dim=1)
          z_f = F.normalize(z_f, dim=1)
          #z_t_aug = F.normalize(z_t_aug, dim=1)
          #z_f_aug = F.normalize(z_f_aug, dim=1)
          h_t = F.normalize(h_t, dim=1)
          h_f = F.normalize(h_f, dim=1)
          h_t_aug = F.normalize(h_t_aug, dim=1)
          h_f_aug = F.normalize(h_f_aug, dim=1)

          """Compute Pre-train loss with SupConLoss"""

          criterion_supcon = SupConLoss()
          domain_criterion = nn.CrossEntropyLoss()

          feat_t_supcon = torch.cat([h_t.unsqueeze(1), h_t_aug.unsqueeze(1)], dim=1)
          l_t_supcon = criterion_supcon(feat_t_supcon, labels)

          feat_f_supcon = torch.cat([h_f.unsqueeze(1), h_f_aug.unsqueeze(1)], dim=1)
          l_f_supcon = criterion_supcon(feat_f_supcon, labels)

          features_supcon = torch.cat([z_t.unsqueeze(1), z_f.unsqueeze(1)], dim=1)
          l_supcon = criterion_supcon(features_supcon, labels)

          lam = 0.5   #0.1  0.2 to test 1.0
          lambda_adv = 0.1  #0.1 0.4
          fea_concat = torch.cat((z_t,z_f), dim=1)

          domain_preds = domain_classifier(fea_concat, alpha=1.0)
          pred_domains = torch.argmax(domain_preds, dim=1)
          batch_domain_acc = (pred_domains == domains).float().mean().item()

          total_domain_acc += batch_domain_acc
          num_batches += 1
          loss_domain = domain_criterion(domain_preds, domains)
          loss = (l_supcon + lam*(l_t_supcon+l_f_supcon) + lambda_adv*loss_domain)
          total_loss.append(loss.item())
          loss.backward()
          #encoder_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=float("inf"))
          #domain_norm = torch.nn.utils.clip_grad_norm_(domain_classifier.parameters(), max_norm=float("inf"))

          #print(f"Encoder: {encoder_norm:.2f}, "
          #      f"Domain: {domain_norm:.2f}")
          #torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)     #new
          #torch.nn.utils.clip_grad_norm_(domain_classifier.parameters(), 5.0)
          model_optimizer.step()
          domain_optimizer.step()
          #current_step += 1

    #print('Pretraining: overall loss:{}'.format(loss))
    avg_domain_acc = total_domain_acc / num_batches
    ave_loss = torch.tensor(total_loss).mean()
    print(
        f"Pretrain Loss: {ave_loss:.4f} | "
        f"Domain Loss: {loss_domain.item():.4f} | "
        f"Domain Acc: {avg_domain_acc:.4f}"
    )

    return ave_loss, avg_domain_acc

# Commented out IPython magic to ensure Python compatibility.
def model_finetune(model, model_optimizer, val_dl, device, training_mode, classifier, classifier_optimizer, domain_classifier, domain_optimizer):
    global labels, pred_numpy, fea_concat_flat
    model.train()
    classifier.train()
    domain_classifier.train()

    total_loss = []
    total_acc = []
    total_auc = []
    total_prc = []
    total_acc_testing = []
    criterion = nn.CrossEntropyLoss()
    domain_criterion = nn.CrossEntropyLoss()
    outs = np.array([])
    trgs = np.array([])
    feas = np.array([])
    filenm_all = []   # pour accumuler les filenames
    dmns = np.array([])
    #total_steps = num_epoch_finetune * len(val_dl)
    #current_step = 0

    for data, labels, aug1, data_f, aug1_f, filenm, domains in val_dl:
        # filenm : [batch_size, max_filename_length]
        data, labels = data.float().to(device), labels.long().to(device)
        data_f = data_f.float().to(device)
        aug1 = aug1.float().to(device)
        aug1_f = aug1_f.float().to(device)
        domains = domains.long().to(device)

        model_optimizer.zero_grad()
        classifier_optimizer.zero_grad()
        domain_optimizer.zero_grad()

        #p = float(current_step) / total_steps
        # Appliquer la formule de Ganin et al.
        #current_alpha = 2.0 / (1.0 + np.exp(-10 * p)) - 1.0

        # --------- embeddings ----------
        h_t, z_t, h_f, z_f = model(data, data_f)
        h_t_aug, z_t_aug, h_f_aug, z_f_aug = model(aug1, aug1_f)
        z_t = F.normalize(z_t, dim=1)
        z_f = F.normalize(z_f, dim=1)
        h_t = F.normalize(h_t, dim=1)
        h_f = F.normalize(h_f, dim=1)
        h_t_aug = F.normalize(h_t_aug, dim=1)
        h_f_aug = F.normalize(h_f_aug, dim=1)
        features_supcon = torch.cat([z_t.unsqueeze(1), z_f.unsqueeze(1)], dim=1)

        criterion_supcon = SupConLoss()
        l_supcon = criterion_supcon(features_supcon, labels)

        feat_t_supcon = torch.cat([h_t.unsqueeze(1), h_t_aug.unsqueeze(1)], dim=1)
        l_t_supcon = criterion_supcon(feat_t_supcon, labels)

        feat_f_supcon = torch.cat([h_f.unsqueeze(1), h_f_aug.unsqueeze(1)], dim=1)
        l_f_supcon = criterion_supcon(feat_f_supcon, labels)

        # --------- classification -------
        fea_concat = torch.cat((z_t, z_f), dim=1)
        #fea_concat = torch.cat((h_t, h_f), dim=1)
        predictions = classifier(fea_concat)
        fea_concat_flat = fea_concat.reshape(fea_concat.shape[0], -1)
        loss_p = criterion(predictions, labels)
        lam = 0.0   #0.1  0.2 to test 1.0
        beta = 1.0   #0.01
        lambda_adv = 0.1  #0.1   0.4  0.05   0.0
        #loss = beta * l_supcon + loss_p + lam*(l_t_supcon + l_f_supcon)
        #lam = 0.1
        #loss = loss_p + l_TF + lam*(loss_t + loss_f)
        #domain_preds = domain_classifier(fea_concat, alpha=current_alpha)
        domain_preds = domain_classifier(fea_concat, alpha=1.0)
        loss_domain = domain_criterion(domain_preds, domains)
        loss = (beta*l_supcon + loss_p + lam*(l_t_supcon + l_f_supcon) + lambda_adv*loss_domain)

        acc_bs = labels.eq(predictions.detach().argmax(dim=1)).float().mean()
        onehot_label = F.one_hot(labels)
        pred_numpy = predictions.detach().cpu().numpy()

        if np.isnan(pred_numpy).any():
            print("Skipping AUC and PRC calculation for batch due to NaN in predictions.")
            auc_bs = float(0)
            prc_bs = float(0)
        else:
            try:
                auc_bs = roc_auc_score(
                    onehot_label.detach().cpu().numpy(),
                    pred_numpy,
                    average="macro",
                    multi_class="ovr"
                )
            except ValueError as e:
                print(f"Could not compute AUC for batch: {e}")
                auc_bs = float(0)

            try:
                prc_bs = average_precision_score(
                    labels.detach().cpu().numpy(),
                    pred_numpy[:, 1]
                )
            except ValueError as e:
                print(f"Could not compute PRC for batch: {e}")
                prc_bs = float(0)

        total_acc.append(acc_bs)
        total_auc.append(auc_bs)
        total_prc.append(prc_bs)
        total_loss.append(loss.item())
        loss.backward()
        #encoder_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=float("inf"))
        #classifier_norm = torch.nn.utils.clip_grad_norm_(classifier.parameters(), max_norm=float("inf"))
        #domain_norm = torch.nn.utils.clip_grad_norm_(domain_classifier.parameters(), max_norm=float("inf"))

        #print(f"Encoder: {encoder_norm:.2f}, "
        #      f"Classifier: {classifier_norm:.2f}, "
        #      f"Domain: {domain_norm:.2f}")
        #torch.nn.utils.clip_grad_norm_(model.parameters(), 9.0)            #new
        #torch.nn.utils.clip_grad_norm_(classifier.parameters(), 9.0)  #new
        #torch.nn.utils.clip_grad_norm_(domain_classifier.parameters(), 9.0)  #new
        model_optimizer.step()
        classifier_optimizer.step()
        domain_optimizer.step()
        #current_step += 1

        if training_mode != "pre_train":
            pred = predictions.max(1, keepdim=True)[1]
            outs = np.append(outs, pred.cpu().numpy())
            trgs = np.append(trgs, labels.data.cpu().numpy())
            feas = np.append(feas, fea_concat_flat.data.cpu().numpy())
            filenm_all.append(filenm.cpu())  # accumuler les filenames de ce batch
            #dmns = np.append(dmns, domains.data.cpu().numpy())

    feas = feas.reshape([len(trgs), -1])

    # concaténer les filenames sur la dimension batch
    if len(filenm_all) > 0:
        filenm_cat = torch.cat(filenm_all, dim=0)   # shape: [N_samples, max_filename_length]
    else:
        filenm_cat = torch.empty(0, dtype=torch.long)

    labels_numpy = labels.detach().cpu().numpy()
    pred_numpy = np.argmax(pred_numpy, axis=1)
    precision = precision_score(labels_numpy, pred_numpy, average='macro', zero_division=0)
    recall = recall_score(labels_numpy, pred_numpy, average='macro')
    F1 = f1_score(labels_numpy, pred_numpy, average='macro')
    ave_loss = torch.tensor(total_loss).mean()
    ave_acc = torch.tensor(total_acc).mean()
    ave_auc = torch.tensor(total_auc).mean()
    ave_prc = torch.tensor(total_prc).mean()

    print(' Finetune: loss = %.4f| Acc=%.4f | Precision = %.4f | Recall = %.4f | F1 = %.4f| AUROC=%.4f | AUPRC = %.4f'
           % (ave_loss, ave_acc*100, precision * 100, recall * 100, F1 * 100, ave_auc * 100, ave_prc *100))

    # *** nouvelle version du retour ***
    return ave_loss, feas, trgs, ave_acc, precision, F1, recall, filenm_cat
