# -*- coding: utf-8 -*-
"""ASD_trainer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WyJBABK3MVUUZOq9e4OUkfy1C85pblT3
"""

import os
import umap
import csv
import numpy as np
import seaborn as sns
import torch
import torch.nn.functional as F
import src.utils.hyperparameters_asd as cfg
import src.utils.utils_asd as utl
import matplotlib.pyplot as plt
#sys.path.append("..")
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from collections import defaultdict
from src.training.train_asd import model_pretrain, model_finetune
from src.evaluation.test_asd import model_test_individual_level, model_validate
from src.utils.utils_asd import MetricTracker, analyze_accuracy_by_type, print_metrics
#from src.datasets.dataloader_asd import filename_map

#from model import *
#tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/TFC/Save_dataset/tokenizer")

def ema(data, alpha=0.2):
    smoothed = [data[0]]
    for point in data[1:]:
        smoothed.append(alpha*point + (1-alpha)*smoothed[-1])
    return smoothed

def Trainer(model, model_optimizer, classifier, classifier_optimizer, domain_classifier, domain_optimizer, train_dl, test_dl, device,
            experiment_log_dir, training_mode, filename_map, num_fold):
    #criterion = nn.CrossEntropyLoss()
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(model_optimizer, 'min')
    best_metrics_testing = None

    ####################################################
    """PRE-TRAINING ON SOURCE DATASET"""
    ####################################################
    if training_mode == 'pre_train':
        print('\nPretraining on source dataset in progress\n')
        total_train_loss = []
        for epoch in range(1, cfg.num_epoch_pretrain + 1):
            train_loss, avg_domain_acc = model_pretrain(model, model_optimizer, domain_classifier, domain_optimizer, train_dl, device)
            print(f'Pre-training Epoch : {epoch}', f'Train Loss : {train_loss:.4f}')
            print(f'Domain Acc: {avg_domain_acc:.4f}')
            # save best pretrain model""
            if len(total_train_loss) == 0 or train_loss < min(total_train_loss):
                print('update pretrain model\n')
                os.makedirs(os.path.join(experiment_log_dir, "saved_models_supCon_pretrain"), exist_ok=True)
                chkpoint = {'model_state_dict': model.state_dict()}
                torch.save(chkpoint, os.path.join(experiment_log_dir, "saved_models_supCon_pretrain", f'ckp_last.pt'))

            total_train_loss.append(train_loss)

        print('Pretrained model is stored at folder:{}'.format(experiment_log_dir+'saved_models_supCon_pretrain/'+'ckp_last.pt'))
        loss_save_dir = os.path.join(experiment_log_dir, "loss_curves")
        os.makedirs(loss_save_dir, exist_ok=True)
        np.save(os.path.join(loss_save_dir, "datasetA_train_loss.npy"), np.array(total_train_loss))
        best_metrics = {"status": "pre_trained"}

    ####################################################
    """PREDICTION USING THE BEST CLASSIFIER and MODEL"""
    ####################################################
    if training_mode == 'prediction':
        tracker_indiv_level = MetricTracker() # Initialize tracker
        tracker_file_level = MetricTracker()
        print('\n--->PREDICTION ON TEST DATASET')
        model.load_state_dict(torch.load(os.path.join(experiment_log_dir, "saved_models_supCon_prediction", f'ckp_last_prediction.pt'), weights_only=True))
        classifier.load_state_dict(torch.load(os.path.join(experiment_log_dir, "saved_models_supCon_prediction", f'classifier_prediction.pt'), weights_only=True))


        """Testing in Individual-Level"""
        print("\n===Testing in Individual-Level===")
        print("\nIndividual Results:")
        individual_results, metrics_indiv_level, class_dist_indiv = model_test_individual_level(model, test_dl, device, classifier, filename_map)
        # ======================================================
        y_true = metrics_indiv_level['y_true']
        y_pred = metrics_indiv_level['y_pred']
        # Confusion Matrix (Individual Level)
        cm = confusion_matrix(y_true, y_pred)
        # Normalize confusion matrix (optional but recommended)
        cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        class_labels = ['NonASD', 'ASD']
        # Print raw confusion matrix
        print("\nConfusion Matrix (Counts):")
        print(cm)
        # Print normalized confusion matrix
        print("\nConfusion Matrix (Normalized):")
        print(np.round(cm_normalized, 3))

        # Optional detailed classification report
        print("\nClassification Report:")
        print(classification_report(
            y_true,
            y_pred,
            target_names=class_labels,
            zero_division=0
        ))
        # Plot confusion matrix
        plt.figure(figsize=(6,5))
        sns.heatmap(
            cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=class_labels,
            yticklabels=class_labels
        )
        plt.xlabel("Predicted Label")
        plt.ylabel("True Label")
        plt.title("Individual-Level Confusion Matrix")
        plt.tight_layout()
        plt.show()
        # ======================================================

        for ind_id, res in individual_results.items():
            status = "✓" if res['prediction'] == res['true_label'] else "✗"
            print(f"{ind_id}: {status} Pred={res['prediction']} (True={res['true_label']}) "
                  f"Files={res['num_files']} Chunks={res['num_chunks']} "
                  f"Confidence={res['confidence']:.2f} Agreement={res['agreement']}")

        # Update tracker (using accuracy score as key metric)
        tracker_indiv_level.update(metrics_indiv_level, epoch=25, key='accuracy')
        print(f"\n***Individual-level testing unseen data:   Number of individus: {len(individual_results)} ({class_dist_indiv})")
        tracker_indiv_level.print_best(metrics_indiv_level)

        output_csv_path_indiv = os.path.join(experiment_log_dir, "saved_models_supCon_prediction", f'predictions_new_data_indiv.csv')
        with open(output_csv_path_indiv, mode='w', newline='', encoding='utf-8') as f:
            fieldnames = ['ind_id', 'prediction', 'true_label', 'num_files', 'num_chunks', 'confidence', 'agreement', 'status']
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()

            for ind_id, res in individual_results.items():
                # On garde CORRECT/INCORRECT pour faciliter le traitement Pandas plus tard
                status = "CORRECT" if res['prediction'] == res['true_label'] else "INCORRECT"
                writer.writerow({
                    'ind_id': ind_id,
                    'prediction': res['prediction'],
                    'true_label': res['true_label'],
                    'num_files': res['num_files'],
                    'num_chunks': res['num_chunks'],
                    'confidence': round(res['confidence'], 4),
                    'agreement': res['agreement'],
                    'status': status
                })
        
        print(f"✅ Fichier individus sauvegardé : {output_csv_path_indiv}")
        analyze_accuracy_by_type(output_csv_path_indiv, id_column='ind_id')
        return y_true, y_pred

    ####################################################
    """FINE-TUNING, VALIDATION AND TEST"""
    ####################################################
    if training_mode == 'fine_tune_validation_test':
        """fine-tune"""
        print('\nFINETUNING ON TARGET DATASET = SOURCE DATASET')

        performance_list = []
        total_f1 = []
        total_recall = []
        total_acc = []
        total_acc_testing = []
        total_precision = []
        accuracy_indiv_level_total = []
        accuracy_file_level_total = []
        tracker_indiv_level = MetricTracker() # Initialize tracker
        tracker_indiv_level_valid = MetricTracker() # Initialize tracker
        tracker_file_level = MetricTracker()
        total_finetune_loss = []
        total_validation_loss = []
        global emb_finetune, label_finetune, emb_test, label_test

        for epoch in range(1, cfg.num_epoch_finetune + 1):
            print(f'\nEpoch : {epoch}')
            finetune_loss, emb_finetune, label_finetune, Acc, Precision, F1, Recall, filenm = model_finetune(model, model_optimizer, train_dl,
                                 device, training_mode, classifier=classifier, classifier_optimizer=classifier_optimizer, domain_classifier=domain_classifier, domain_optimizer=domain_optimizer)

            scheduler.step(finetune_loss)
            total_finetune_loss.append(finetune_loss)

            #from sklearn.svm import SVC
            #svm = SVC(kernel='linear', C=1.0)
            #svm.fit(emb_finetune, label_finetune)


            # save best fine-tuning model""
            if len(total_acc) == 0 or Acc > max(total_acc):
                print('update fine-tuned model')
                #os.makedirs('experiments_logs/finetunemodel/', exist_ok=True)
                os.makedirs(os.path.join(experiment_log_dir, "saved_models_supCon_finetune"), exist_ok=True)
                torch.save(model.state_dict(), os.path.join(experiment_log_dir, "saved_models_supCon_finetune", f'ckp_last.pt'))
                torch.save(classifier.state_dict(), os.path.join(experiment_log_dir, "saved_models_supCon_finetune", f'classifier.pt'))

            total_acc.append(Acc)
            total_precision.append(Precision)
            total_recall.append(Recall)
            total_f1.append(F1)


            # load best finetune model and evaluate on the test set
            #print('\n--->PREDICTION ON TEST DATASET')

            #Testing in Individual-Level for each finetune model
            print("\n===Testing in Individual-Level===")
            #print("\nIndividual Results:")
            individual_results, metrics_indiv_level, class_dist_indiv = model_test_individual_level(model, test_dl, device, classifier, filename_map)

            validation_loss, validation_acc = model_validate(model, test_dl, device, classifier)

            #scheduler.step(validation_loss)

            total_validation_loss.append(validation_loss)   #/////////////////////////////////////

            #Update tracker (using accuracy score as key metric)
            tracker_indiv_level.update(metrics_indiv_level, epoch, key='accuracy')
            metrics_ep = print_metrics(metrics_indiv_level, epoch)
            Acc_testing = metrics_ep['accuracy']
            #Save the model and classifier achieved
            if len(total_acc_testing) == 0 or Acc_testing >= max(total_acc_testing):
              os.makedirs(os.path.join(experiment_log_dir, "saved_models_supCon_prediction"), exist_ok=True)
              #chkpoint = f"{epoch}_ckp_last.pt"
              chkpoint = "ckp_last_prediction.pt"
              #classifierpoint = f"{epoch}_classifier.pt"
              classifierpoint = "classifier_prediction.pt"
              torch.save(model.state_dict(), os.path.join(experiment_log_dir, "saved_models_supCon_prediction", chkpoint))
              torch.save(classifier.state_dict(), os.path.join(experiment_log_dir, "saved_models_supCon_prediction", classifierpoint))

            total_acc_testing.append(Acc_testing)

            """UMAP visualization of test embeding"""
            #visualization(emb_test, label_test, epoch, "testing")


        if num_fold == 1:
            emb_finetune = torch.from_numpy(emb_finetune)
            emb_finetune = F.normalize(emb_finetune,p=2,dim=1)
            utl.visualization_tsne(
                emb=emb_finetune,
                lab=label_finetune,
                filenm=filenm,              # tensor [N, max_len]
                filename_map=filename_map,  # dict {tuple(tokens): "200122_1453_..." }
                ep=epoch,
                acc=Acc,
                precision=Precision,
                recall=Recall,
                f1=F1,
                train_mode="finetune"
            )
        
        loss_save_dir = os.path.join(experiment_log_dir, "loss_curves")

        print("\n############# BEST PERFORMANCE FOR TF-C ASD MODEL USING SUPERVISED CONTRASTIVE LOSS ####################\n")
        #print(f"\n***Number total of individus: {Nb_ASD + Nb_NonASD} (ASD: {Nb_ASD} , NonASD: {Nb_NonASD})")
        print('===BEST FINETUNING PERFORMANCE===')
        print("***Acc = %.4f| Precision = %.4f| Recall = %.4f | F1 = %.4f"% (max(total_acc), max(total_precision), max(total_recall), max(total_f1)))
        best_metrics_finetune = {
        'accuracy': max(total_acc),
        'precision': max(total_precision),
        'recall': max(total_recall),
        'f1': max(total_f1)
        }

        #print(f"Best KNN Acc : {knn_acc} F1 : {max(KNN_f1)}")

        print("\n===BEST PREDICTION=== ")
        print(f"\n***Individual-level testing unseen data:   Number of individus: ({class_dist_indiv})")
        best_metrics_testing = tracker_indiv_level.print_best(metrics_indiv_level)

        print("\n####################### Experimentation is Done! #########################")

        if best_metrics_testing is None:
            # Sécurité au cas où aucun mode ne correspondrait
            return {"accuracy": 0, "f1": 0, "precision": 0, "recall": 0}

        # Plot training/validation curves
        train_smooth = ema(total_finetune_loss, alpha=0.2)
        val_smooth = ema(total_validation_loss, alpha=0.2)
        epochs = range(1, len(total_finetune_loss) + 1)
        plt.figure(figsize=(8,6))
        plt.plot(epochs, train_smooth, label='Training Loss', linewidth=2)
        plt.plot(epochs, val_smooth, label='Validation Loss', linewidth=2)
        plt.xlabel('Epoch')
        plt.ylabel('Loss')
        plt.title(f'Training vs Validation Loss - Fold {num_fold}')
        plt.legend()
        plt.grid(True, alpha=0.3)
        fig_name = f"train_validation_loss_fold_{num_fold}.png"
        plt.savefig(
            os.path.join(loss_save_dir, fig_name),
            dpi=600,
            bbox_inches='tight'
        )
        plt.close()
        return best_metrics_testing, best_metrics_finetune
