# -*- coding: utf-8 -*-
"""ASD_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rQzHkZ0AfxSRByH7Ja2uKm0isVETR1RR
"""

from torch import nn
import torch
from torch.nn import TransformerEncoder, TransformerEncoderLayer
import math
import src.utils.hyperparameters_asd as cfg

# Fix for d_model
d_model = cfg.d_model[0] if isinstance(cfg.d_model, tuple) else cfg.d_model

# Fix for dim_feedforward
dim_feedforward = cfg.dim_feedforward[0] if isinstance(cfg.dim_feedforward, tuple) else cfg.dim_feedforward

class PositionalEncoding(nn.Module):
    def __init__(self, d_model: int, max_len: int = 5000):
        super().__init__()
        position = torch.arange(max_len).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2) * (-math.log(10000.0) / d_model))
        pe = torch.zeros(max_len, d_model)
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return x + self.pe[:x.size(1)]


"""Two contrastive encoders"""
class TFC(nn.Module):
    def __init__(self):
        super(TFC, self).__init__()
        # Project raw input to d_model if needed (e.g., from seq_len to d_model)
        self.projection = nn.Linear(cfg.patch_size, d_model)

        # Add positional encoders
        self.pos_encoder_t = PositionalEncoding(d_model, max_len=cfg.TSlength_aligned)
        self.pos_encoder_f = PositionalEncoding(d_model, max_len=cfg.TSlength_aligned)
        # Transformer encoder
        encoder_layers_t = TransformerEncoderLayer(
            d_model=d_model,
            nhead=cfg.nhead,                           # Must divide d_model (e.g., 8 for d_model=768)
            dim_feedforward=int(dim_feedforward),  # 4*d_model
            dropout=cfg.dropout,
            batch_first=True,
        )
        self.transformer_encoder_t = TransformerEncoder(encoder_layers_t, num_layers=cfg.num_layers)

        self.projector_t = nn.Sequential(
            nn.Linear(d_model, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.Linear(256, 128)
        )

        encoder_layers_f = TransformerEncoderLayer(
            d_model=d_model,
            nhead=cfg.nhead,
            dim_feedforward=int(dim_feedforward),  # 4*d_model
            dropout=cfg.dropout,
            batch_first=True,
        )
        self.transformer_encoder_f = TransformerEncoder(encoder_layers_f, num_layers=cfg.num_layers)

        self.projector_f = nn.Sequential(
            nn.Linear(d_model, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.Linear(256, 128)
        )

    def forward(self, x_in_temps, x_in_freq):
        x_in_proj_t = self.projection(x_in_temps)
        x_in_proj_f = self.projection(x_in_freq)
        x_in_t = self.pos_encoder_t(x_in_proj_t)
        x_in_f = self.pos_encoder_f(x_in_proj_f)

        """Use Transformer"""
        #x = self.transformer_encoder_t(x_in_t)
        x = self.transformer_encoder_t(x_in_proj_t)
        h_time = x.reshape(x.shape[0], -1)
        #h_time = x.mean(dim=1)

        """Cross-space projector"""
        z_time = self.projector_t(h_time)
        #z_time = h_time

        """Frequency-based contrastive encoder"""
        #f = self.transformer_encoder_f(x_in_f)
        f = self.transformer_encoder_f(x_in_proj_f)
        h_freq = f.reshape(f.shape[0], -1)
        #h_freq = f.mean(dim=1)

        """Cross-space projector"""
        z_freq = self.projector_f(h_freq)
        #z_freq = h_freq

        return h_time, z_time, h_freq, z_freq

"""Downstream classifier only used in finetuning"""
import torch.nn.functional as F

class target_classifier(nn.Module):

    def __init__(self):

        super(target_classifier, self).__init__()

        self.fc1 = nn.Linear(256, 128)

        self.fc2 = nn.Linear(128, 64)

        self.fc3 = nn.Linear(64, cfg.num_classes_target)

        self.dropout = nn.Dropout(0.3)

    def forward(self, emb):

        x = emb.reshape(emb.shape[0], -1)

        x = self.fc1(x)

        x = F.gelu(x)

        x = self.dropout(x)

        x = self.fc2(x)

        x = F.gelu(x)

        x = self.dropout(x)

        x = self.fc3(x)

        return x

"""
class target_classifier(nn.Module):
    def __init__(self):
        super(target_classifier, self).__init__()
        self.logits = nn.Linear(2*128, 64)
        self.logits_simple = nn.Linear(64, cfg.num_classes_target)

    def forward(self, emb):
        emb_flat = emb.reshape(emb.shape[0], -1)
        emb = torch.sigmoid(self.logits(emb_flat))
        pred = self.logits_simple(emb)
        return pred




class target_classifier(nn.Module):

    def __init__(self):

        super(target_classifier, self).__init__()

        self.logits = nn.Linear(2 * 128, 128)

        self.dropout = nn.Dropout(0.2)
        #self.dropout = nn.Dropout(0.2)
        self.logits2 = nn.Linear(128, 64)

        self.logits3 = nn.Linear(64, cfg.num_classes_target)

    def forward(self, emb):

        # ==========================================
        # Flatten embeddings
        # ==========================================

        emb_flat = emb.reshape(emb.shape[0], -1)
        # Layer 1
        x = self.logits(emb_flat)
        x = torch.relu(x)
        x = self.dropout(x)
        # Layer 2
        x = self.logits2(x)
        x = torch.relu(x)
        x = self.dropout(x)
        # Output layer
        # ==========================================
        pred = self.logits3(x)

        return pred
"""




import torch.nn as nn
from torch.autograd import Function
"""
class DomainClassifier(nn.Module):
    def __init__(self, num_domains=4):
        super().__init__()

        self.grl = GradientReversalLayer(alpha=1.0)

        self.net = nn.Sequential(
            nn.Linear(256, 128),
            nn.BatchNorm1d(128),
            nn.LeakyReLU(0.1),

            nn.Dropout(0.3),

            nn.Linear(128, 64),
            nn.BatchNorm1d(64),
            nn.LeakyReLU(0.1),

            nn.Dropout(0.3),

            nn.Linear(64, num_domains)
        )

    def forward(self, x, alpha=None):
        x = self.grl(x, alpha)
        return self.net(x)



class DomainClassifier(nn.Module):
    def __init__(self):
        super(DomainClassifier, self).__init__()
        self.grl = GradientReversalLayer(alpha=1.0)
        self.net = nn.Sequential(
            nn.Linear(256, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 3)
        )

    def forward(self, x):
        # Transmet l'alpha dynamique à la GRL
        x = self.grl(x)
        return self.net(x)


from torch.autograd import Function
class GradientReverseFunction(Function):
    @staticmethod
    def forward(ctx, x, alpha):
        ctx.alpha = alpha
        return x.view_as(x)

    @staticmethod
    def backward(ctx, grad_output):
        return -ctx.alpha * grad_output, None

class GradientReversalLayer(nn.Module):
    def __init__(self, alpha=1.0):
        super().__init__()
        self.alpha = alpha
    def forward(self, x, alpha=None):
        if alpha is not None:
            self.alpha = alpha
        return GradientReverseFunction.apply(x, self.alpha)
"""
class GradientReverseFunction(Function):
    @staticmethod
    def forward(ctx, x, alpha):
        ctx.alpha = alpha
        return x.view_as(x)

    @staticmethod
    def backward(ctx, grad_output):
        return -ctx.alpha * grad_output, None

class GradientReversalLayer(nn.Module):
    def forward(self, x, alpha=1.0):
        return GradientReverseFunction.apply(x, alpha)

class DomainClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.grl = GradientReversalLayer()
        self.net = nn.Sequential(
            nn.Linear(256, 128),
            nn.BatchNorm1d(128),
            #nn.GroupNorm(8, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 3)
        )

    def forward(self, x, alpha=1.0):
        x = self.grl(x, alpha)
        return self.net(x)
